name: Testing Actions CM

on:
  push:
    branches: [ "master" ]

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install npm  
      run: npm install -g npm
    - name: 'hello word'
      run: echo "Hello Word" 
    - name: muestra el contenido del directorio
      run: ls -la
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4.2.2
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: 20.x
  #       cache: 'npm'
  #   - name: Create .env file
  #     run: |
  #       echo '{
  #         "Dev": {
  #           "FIREBASE_API_KEY": "${{ secrets.VITE_FIREBASE_API_KEY }}",
  #           "FIREBASE_AUTH_DOMAIN": "${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}",
  #           "FIREBASE_PROJECT_ID": "${{ secrets.VITE_FIREBASE_PROJECT_ID }}",
  #           "FIREBASE_STORAGE_BUCKET": "${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}",
  #           "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}",
  #           "FIREBASE_APP_ID": "${{ secrets.VITE_FIREBASE_APP_ID }}"
  #         }
  #       }' > .env-cmdrc.json
  #   - run: npm ci

  #   - name: Run tests
  #     run: npm test

  #   - name: Run build
  #     run: npm run build

  #   - name: Cargar el build como artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: build
  #       path: dist/
  #       retention-days: 1

  #   - name: 'hello word'
  #     run: echo "Hello Word" 
  #   - name: print fecha
  #     run: date
  #   - name: muestra el contenido del directorio
  #     run: ls -la

  # app-tests:
  #   runs-on: ubuntu-latest

  #   steps:

  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'

  #     - name: Install NPM dependencies
  #       run: npm install

  #     - name: Check javaScript code style
  #       run: npm run lint

  #     - name: Execute javaScript tests
  #       run: npm run coverage

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}